name       : tor
version    : 0.3.0.8
release    : 8
source     :
    - https://dist.torproject.org/tor-0.3.0.8.tar.gz : 663a3ba7b8a124c0f8a7351eaa2dda6fd518de3f3c4ee28fff869bfb03860d48
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libsystemd)
    - pkgconfig(openssl)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm0700 -o 43 -g 43 "$workdir/var/lib/tor"
    mv $installdir/etc/tor/torrc.sample $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
