name       : tor
version    : 0.2.8.9
release    : 3
source     :
    - https://www.torproject.org/dist/tor-0.2.8.9.tar.gz : 3f5c273bb887be4aff11f4d99b9e2e52d293b81ff4f6302b730161ff16dc5316
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libsystemd)
    - pkgconfig(openssl)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm0700 -o 43 -g 43 "${pkgdir}/var/lib/tor"
    mv $installdir/etc/tor/torrc.sample $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
