name       : tor
version    : 0.4.7.10
release    : 38
source     :
    - https://dist.torproject.org/tor-0.4.7.10.tar.gz : 647e56dfa59ea36dab052027fcfc7663905c826c03509363c456900ecd435a5b
homepage   : https://www.torproject.org/
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libzstd)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/etc/tor/torrc.sample
    install -Dm00644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm00644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
    install -Dm00644 $pkgfiles/tor.sysusers $installdir/%libdir%/sysusers.d/tor.conf
    install -Dm00644 $pkgfiles/tor.tmpfiles $installdir/%libdir%/tmpfiles.d/tor.conf
