name       : tor
version    : 0.4.4.5
release    : 28
source     :
    - https://dist.torproject.org/tor-0.4.4.5.tar.gz : a45ca00afe765e3baa839767c9dd6ac9a46dd01720a3a8ff4d86558c12359926
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/etc/tor/torrc.sample
    install -Dm0644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
    install -Dm0644 $pkgfiles/tor.sysusers $installdir/%libdir%/sysusers.d/tor.conf
    install -Dm0644 $pkgfiles/tor.tmpfiles $installdir/%libdir%/tmpfiles.d/tor.conf
