name       : tor
version    : 0.3.0.7
release    : 7
source     :
    - https://dist.torproject.org/tor-0.3.0.7.tar.gz : 9640c4448ef3cad7237c68ed6984e705db8fb2b9d6bb74c8815d01bb06527d02
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libsystemd)
    - pkgconfig(openssl)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm0700 -o 43 -g 43 "$workdir/var/lib/tor"
    mv $installdir/etc/tor/torrc.sample $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
