name       : tor
version    : 0.2.9.9
release    : 5
source     :
    - https://dist.torproject.org/tor-0.2.9.9.tar.gz : 33325d2b250fd047ba2ddc5d11c2190c4e2951f4b03ec48ebd8bf0666e990d43
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libsystemd)
    - pkgconfig(openssl)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -dm0700 -o 43 -g 43 "$workdir/var/lib/tor"
    mv $installdir/etc/tor/torrc.sample $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
