name       : tor
version    : 0.3.3.9
release    : 14
source     :
    - https://www.torproject.org/dist/tor-0.3.3.9.tar.gz : 85346b4d026e6a041c8e326d2cc64b5f5361b032075c89c5854f16dbc02fce6f
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libsystemd)
    - pkgconfig(openssl)
    - asciidoc
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/etc/tor/torrc.sample
    install -Dm0644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm0644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
    install -Dm0644 $pkgfiles/tor.sysusers $installdir/%libdir%/sysusers.d/tor.conf
    install -Dm0644 $pkgfiles/tor.tmpfiles $installdir/%libdir%/tmpfiles.d/tor.conf
